/* tslint:disable */
/* eslint-disable */
export const __wbg_raytracerapp_free: (a: number, b: number) => void;
export const raytracerapp_new: () => number;
export const raytracerapp_parse_scene: (a: number, b: number, c: number) => [number, number, number];
export const raytracerapp_is_ready: (a: number) => number;
export const raytracerapp_is_complete: (a: number) => number;
export const raytracerapp_get_needed_resources: (a: number) => [number, number];
export const raytracerapp_initialize: (a: number, b: number, c: number, d: any, e: any) => [number, number];
export const raytracerapp_raytrace_next_pixels: (a: number, b: number) => any;
export const raytracerapp_rescan: (a: number) => [number, number];
export const raytracerapp_set_dimensions: (a: number, b: number, c: number) => [number, number];
export const raytracerapp_render_to_canvas: (a: number) => [number, number];
export const full_render: (a: number, b: number, c: any, d: any, e: any) => [number, number];
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_start_worker: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
