baseURL = 'https://holmdahl.io'
languageCode = 'en-us'
title = 'holmdahl.io'
theme = 'hugo-PaperMod'

[params]
mainSections = ["posts", "projects"]
description = "Reece Holmdahl's Portfolio"
keywords = [
    "Software Engineer I",
    "Software Engineer Minnesota",
    "Software Engineer Remote",
    "Software Engineer I Minnesota",
    "Software Engineer I Remote",
    "Professional",
    "Software Engineer",
    "Backend Engineer",
    "Full Stack",
    "Software Development",
    "Full Stack Developer",
    "Full Stack Software Engineer",
    "Full Stack Software Developer",
    "Backend Software Engineer",
    "Backend Software Developer",
    "Recent Graduate",
    "Computer Science Graduate",
    "Computer Science Undergraduate",
    "Computer Science",
    "Open to work",
    "Employers",
    "Looking for work",
    "Contact",
    "Contact Me",
    "About",
    "Resume",
    "CV",
    "Projects",
    "Reece",
    "Reece portfolio",
    "Reece Holmdahl",
    "Reece Holmdahl portfolio",
    "Reece Holmdahl Minnesota",
    "Reece Minnesota",
    "Holmdahl Minnesota",
    "Holmdahl",
    "Holmdahl Portfolio",
    "Reese Holmdahl",
    "Reese Holmdahl portfolio",
    "Reese Portfolio",
    "Software Engineer",
    "Mathematician",
    "Blog",
    "Portfolio",
    "holmdahl.io",
    "rholmdahl",
    "r holmdahl",
    "r at holmdahl dot io",
    "rholmdahl@gmail.com",
    "rholmdahl at gmail dot com",
    "reece@holmdahl.io",
    "reece at holmdahl dot io",
    "r@holmdahl.io",
    "holmdahl.io website",
    "holmdahl.io portfolio",
    "software engineer portfolio",
    "backend engineer portfolio",
    "reece software engineer portfolio",
    "reece backend engineer portfolio",
    "reece fullstack engineer portfolio",
]

[menus]
main = [
    { name = "Home", url = "/", weight = 1 },
    { name = "Projects", url = "/projects", weight = 2 },
    { name = "Posts", url = "/posts", weight = 3 },
    { name = "About", url = "/about", weight = 4 },
]

[params.profileMode]
enabled = true
title = "Reece Holmdahl"
email = "_reece@holmdahl.io_"
subtitle = "Software Engineer | CS & Math Graduate from UMN"
imageUrl = "img/profile.png"
imageWidth = 250
imageHeight = 250
imageTitle = "Reece at Grand Prismatic Spring, Yellowstone"
buttons = [
    { name = "Resume", url = "/pdf/Reece_Holmdahl_resume.pdf" },
    { name = "Projects", url = "/projects" },
    { name = "Posts", url = "/posts" },
]

[params.socialIcons]
github = { name = "github", url = "https://github.com/reecelikesramen/" }
linkedin = { name = "linkedin", url = "https://www.linkedin.com/in/reeceholmdahl/" }
#instagram = { name = "instagram", url = "https://www.instagram.com/reece.holmdahl/" }

[params.env]
underConstruction = false
author = "Reece Holmdahl"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
# disableHLJS = true
# disableFingerprinting = true
favicon = "icon/favicon.ico"
favicon16x16 = "icon/favicon-16x16.png"
favicon32x32 = "icon/favicon-32x32.png"
apple_touch_icon = "icon/apple-touch-icon.png"

[params.label]
text = "holmdahl.io"
# icon = "profile/profile.jpeg"
# iconHeight = 10

[params.cover]
responsiveImages = true
