name: CI (Build & Deploy with PNPM, Astro, LaTeX)

on:
  push:
    branches:
      - main

jobs:
  # -----------------------------------------------------------------------------------
  # 1) Filter job: check if any of src/, public/, or resume.tex changed
  # -----------------------------------------------------------------------------------
  filter:
    name: Check for relevant changes
    runs-on: ubuntu-latest
    outputs:
      watch: ${{ steps.filter.outputs.watch }}
      resume: ${{ steps.filter.outputs.resume }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Detect changes in src/, public/, or resume.tex
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            watch:
              - 'src/**'
              - 'public/**'
              - 'resume.tex'
            resume:
              - 'resume.tex'

  # -----------------------------------------------------------------------------------
  # 2) Build job: runs only if something under src/, public/, or resume.tex changed
  # -----------------------------------------------------------------------------------
  build:
    name: Build & Deploy
    needs: filter
    if: needs.filter.outputs.watch == 'true'
    runs-on: ubuntu-latest
    
    # Grant GITHUB_TOKEN the permissions required for Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: read    # to checkout the repository
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    defaults:
      run:
        shell: bash

    steps:
      # 2.1) Always check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2.2) Set up Node.js with PNPM cache
      - name: Set up Node.js (v22) & enable pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      # 2.3) Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # 2.4) Install project dependencies with pnpm
      - name: Install dependencies
        run: pnpm install

      # 2.5) Build resume.tex if it changed, output to public/resume.pdf
      - name: Build resume (LaTeX)
        if: needs.filter.outputs.resume == 'true'
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_args: '-output-directory=build'

      - name: Copy resume to public
        if: needs.filter.outputs.resume == 'true'
        run: cp build/resume.pdf public/

      # 2.6) Build Astro site unconditionally
      - name: Build Astro site
        run: pnpm run build

      # 2.7) Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # 2.8) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
